inputDirectory: input
outputDirectory: output
ipadInputDirectory: input-ipad
ipadOutputDirectory: output-ipad
font:
  path: Fredoka-VariableFont_wdth,wght.ttf
  axes: "550,105"
colours:
- backgroundColour: FEF6F0
  textColour: "3B1F14"
- backgroundColour: EDF3FC
  textColour: "0E2646"
- backgroundColour: F4EFF9
  textColour: "2C1545"
- backgroundColour: F0F7F4
  textColour: "163D2C"
screenshots:
- inputBasename: home
  text: "Your simple home|for acne recovery"
- inputBasename: trends
  text: "Understand the trends|that lead to outbreaks"
- inputBasename: gallery
  text: "Save photos to see|on your progress"
- inputBasename: record
  text: "Record regularly|to stay focused"
